@baseUrl = {{$dotenv VITE_SUPABASE_URL}}
@anonKey = {{$dotenv VITE_SUPABASE_ANON_KEY}}

GET {{baseUrl}}/rest/v1/ProductPrices
apikey: {{anonKey}}
Authorization: Bearer {{anonKey}}
Accept: application/json

